branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@google/semantic-release-replace-plugin'
    - replacements:
        - files:
            - build.sbt
          from: version := .*
          to: version := "${nextRelease.version}",
          results:
            - file: build.sbt
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package.json
          from: '\"version\": \".*\"'
          to: '"version": "${nextRelease.version}"'
          results:
            - file: package.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package-lock.json
          from: '\"name\": \"tuples-space-core\",\n  \"version\": \".*\"'
          to: "\"name\": \"tuples-space-core\",\n  \"version\": \"${nextRelease.version}\""
          results:
            - file: package-lock.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - package-lock.json
          from: '\"name\": \"tuples-space-core\",\n      \"version\": \".*\"'
          to: "\"name\": \"tuples-space-core\",\n      \"version\": \"${nextRelease.version}\""
          results:
            - file: package-lock.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - sonar-project.properties
          from: sonar.projectVersion=.*
          to: sonar.projectVersion=${nextRelease.version}
          results:
            - file: sonar-project.properties
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - README.md
          from: 'libraryDependencies \+\+= Seq\(\"io\.github\.cake-lier\" % \"tuples-space-core\" % .*'
          to: "libraryDependencies ++= Seq(\"io.github.cake-lier\" % \"tuples-space-core\" % \"${nextRelease.version}\")"
          results:
            - file: README.md
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - 'semantic-release-license'
  - - '@semantic-release/exec'
    - publishCmd: |
        sbt publishSigned || exit 1;
        sbt sonatypeBundleRelease || exit 2;
      shell: /bin/bash
  - - '@semantic-release/git'
    - assets:
        - build.sbt
        - README.md
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - sonar-project.properties
  - '@semantic-release/github'
